### ISSUE TITLE
Allow to access all loaded operation files 

### ISSUE THREAD

**Issue by dotansimha** [dotansimha/graphql-eslint#25]
Some rules might needs access to other loaded operations - maybe we can have a util on the context level for getting a fragment by name or something like that.

This might be done using ESLint as core, since we need to make sure to load the same files ESLint loaded (as defined in the configuration - `exclude`, `extension` and so on)

**Comment by ilyavolodin** [comment]
Unfortunately, this isn't really possible to do in ESLint, since ESLint lints a file as they load. I.e. even if another file was loaded and linted before, you have no access to its content. ESLint also doesn't guarantee an order of linting, so you can't predict which files will be loaded before the current file.
eslint-plugin-import solved this by basically have a singleton instance that's called from every rule. It will load scan all your dependencies once, and every consecutive request will be served from cache.

**Comment by dotansimha** [comment]
I was thinking to expose a function in the parserServices that will use graphql-tools to load siblings files

**Comment by ilyavolodin** [comment]
Yes, that's possible to do as parserService, but then the parser will always require graphql-config file for any linting. I would love to avoid having another file required for all rules to function.

**Comment by dotansimha** [comment]
@ilyavolodin I was thinking to do that lazily, so the parserService will expose a function the loads (and caches) the graphql files. So it will get loaded only with specific rules, and only if the relevant AST was found, and it will be cached.

**Comment by ilyavolodin** [comment]
But since the order of linting is not guaranteed, you never know when is the last call to the `parserService` is going to occur. More than that, if you lazily cache files, when you lint second file (out of, let's say, 20), you will very incomplete schema.
In order to have predictable caching, linting would have to happen in two stages, and ESLint only does one stage linting. I keep wanting to propose an RFC that would add 2 new hooks for plugins for ESLint, one that happens before any linting begins, and one that happens at the end, once everything is done, but before reports are generated.

**Comment by coreylight** [comment]
I think my project requires this to be able to do any valid linting.
We put our fragments into separate files that get picked up by [graphql codegen](https://graphql-code-generator.com/) correctly. So we'd have to tell the parser to look at those somehow.

**Comment by dotansimha** [comment]
Yeah, @coreylight , that was the exact inspiration for that. 
@ilyavolodin you are right about ESLint loading and execution process, but I don't aim to use ESlint for that. 
I think just like loading the schema for TypeInfo, we can use `graphql-tools` to load all `.graphql` files, and get all relevant operations, and cache it per execution. This way we can allow rules to use siblings operations / all operations to get data. 

The use-case @coreylight suggested is very popular, since it's easier to maintain shared GraphQL fragments in different files, and just reference those by name in the operation file.

I'm doing a small experiment on that now, I will push a draft PR for that soon, just to check how it effects performance and usability :)

**Comment by dontsave** [comment]
My project is also one which distributes fragments and operations across multiple files, which means that this plugin, while great, doesn't suit our needs just yet. I'd love if this feature could be implemented as we could really benefit from it! Thank you for your work here

**Comment by joeboyscout04** [comment]
Will be great to try this out soon!  We also split our operations over multiple files and are looking forward to linting them properly.

**Comment by dotansimha** [comment]
@joeboyscout04 Very soon! I just want to apply fixes to `require-id-when-available`, since I broke it...

**Comment by dotansimha** [comment]
Available in `@graphql-eslint/eslint-plugin@0.5.0`.
