### ISSUE TITLE
Definition for [Validation] rules not found

### ISSUE THREAD

**Issue by the-ult** [dotansimha/graphql-eslint#403]
**Describe the bug**

Using the `Validation` rules:
```json
{
  "overrides": [
    {
      "files": ["*.graphql"],
      "parser": "@graphql-eslint/eslint-plugin",
      "plugins": ["@graphql-eslint"],
      "rules": {
         ...
          "@graphql-eslint/@graphql-eslint/fields-on-correct-type": ["error"],
          "@graphql-eslint/@graphql-eslint/known-argument-names": ["error"],
          "@graphql-eslint/@graphql-eslint/known-type-names": ["error"],
          "@graphql-eslint/@graphql-eslint/no-fragment-cycles": ["error"],
          "@graphql-eslint/@graphql-eslint/no-undefined-variables": ["error"],
          "@graphql-eslint/@graphql-eslint/no-unused-variables": ["error"],
          "@graphql-eslint/@graphql-eslint/overlapping-fields-can-be-merged": ["error"],
          "@graphql-eslint/@graphql-eslint/provided-required-arguments": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-argument-names": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-enum-names": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-field-names": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-input-field-names": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-operation-names": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-type-names": ["error"],
          "@graphql-eslint/@graphql-eslint/unique-variable-names": ["error"],
          "@graphql-eslint/@graphql-eslint/variables-in-allowed-position": ["error"]
       }
    }
  ]
}
```
results in:
```
 error  Definition for rule '@graphql-eslint/@graphql-eslint/fields-on-correct-type' was not found                                            @graphql-eslint/@graphql-eslint/fields-on-correct-type
```

**Expected behavior**
The rule definitions should be available/found

**Environment:**

- OS: MacOS
- `"@graphql-eslint/eslint-plugin": "0.9.1",`
- NodeJS: 15.14.0

**Comment by B2o5T** [comment]
you wrote twice `@graphql-eslint/@graphql-eslint` in your rules

**Comment by the-ult** [comment]
Woow.. I only misted that like 20 times.. 😕 

Rookie mistake.. thanks.

**Comment by Urigo** [comment]
Thank you @the-ult for reporting this issue !

I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems like we are in `stage 0`.

Now in order to advance to `stage 1` we'll need a reproduction somewhere we could run.
Would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a solution (yet).

**Comment by the-ult** [comment]
So.. that was a bit really bad reading of the proper rule names from my end.
Sorry 

Will close the issue.
