### ISSUE TITLE
 @graphql-eslint/naming-convention: query should or should not start with a verb

### ISSUE THREAD

**Issue by DianaSuvorova** [dotansimha/graphql-eslint#450]
For example if

**eslint @graphql-eslint/naming-convention: ["error", {"QueryDefinition": ["camelCase", "shouldStartWithVerb"]}]**

correct: 

```
type Query {
    getUser(id: String): User
}
```

incorrect: 

```
type Query {
    user(id: String): User
}

type Query {
    GetUser(id: String): User
}
```

Let me know if you would be open to this contribution (if this does not exist yet) and if yes what the correct rule configuration format should look like.

I was thinking of letting QueryDefinition take an array of values that can include _shouldStartWithVerb_ and _shouldNotStartWithVerb_

**Comment by dotansimha** [comment]
Hi @DianaSuvorova ! 

I think the term `shouldStartWithVerb` is a bit too specific here because it implies that we enforce any type of verb. 

We have a rule that allows you to enforce specific prefixes for operation name, take a look here: https://github.com/dotansimha/graphql-eslint/blob/1d8502580c518ea89a855bb0db9c3bbda73b0500/docs/rules/avoid-operation-name-prefix.md , so this way you can prevent using specific prefix like `get` / `set`. We can port that into a rule that does something similar for fields, does that work? :)

**Comment by DianaSuvorova** [comment]
@dotansimha thanks for your response!

So our team has decided to follow proto/java 's convention in naming queries. So we actually want to enforce that the suffix such as `get/set` is present. I am not sure if it is possible to configure `avoid-operation-name-prefix` in a way that would enforce this naming convention. As far as I understand the rule we would need to list all entity names such as: `user, product etc` and  we got a lot.

So we actually want the opposite of that rule `avoid-operation-name-prefix` so I wonder if there is a way to generalize either  this one or a `naming-convention` rule.

I was thinking to source the  list of `allowed` prefixes from [verb-corpus](https://www.npmjs.com/package/verb-corpus). Open for better suggestions on how to implement the check.

Thanks,
Diana

**Comment by DianaSuvorova** [comment]
@dotansimha following up on this.

Would you be open to a PR  generalizing the `avoid-operation-name-prefix` rule.
I do understand that best GraphQL practice is exactly to avoid operation name prefix. Although REST and Protobuf are the opposite (your operations are starting with a standard verb such `GET`, `PUT` for REST and get/set/anyVerb for Proto)

So maybe we can extend this rule to:

`@graphql-eslint/operation-name-style: ["error", "always/never", "graphql/proto/rest"]`

Or more explicit:

`@graphql-eslint/operation-name-prefix: ["error", "always/never", "keywords":["ALL_VERBS" ,"get"]}`

I do understand that operations should not start with a verb according to GraphQL best practice. But I still think that consistency is still preferable. Would be happy to elaborate on our use case if that's helpful.

Diana

**Comment by dotansimha** [comment]
PRs are always welcome! I just don't think that mixing external packages for that purpose might be ideal. Seems like this use-case is pretty specific to what you need, and that's why we allow implementing custom rules (and if you see a chance to make it more generic and something that might fit other use-cases - we always welcome contributions). 

@B2o5T What do you think? :)

**Comment by B2o5T** [comment]
What I think is a bad practice in GraphQL to name queries with `get` prefix
But, @DianaSuvorova with `graphql-eslint` you still can force to name your queries with no matter what prefix.

For query like
```gql
type Query {
  user(id: ID!): User
}
```
and with options 
```
# eslint @graphql-eslint/naming-convention: ['error', { QueryDefinition: { style: 'camelCase', prefix: 'get' } }]
````
It's will report an error `Query name "user" should have "get" prefix` according to your needs

**Comment by DianaSuvorova** [comment]
@B2o5T  Beautiful! Just tried it -- works exactly as I need. Apologies for the confusion here. Thank you so much!
