### ISSUE TITLE
Adding support for #graphql as magic comments in addition to /* GraphQL */

### ISSUE THREAD

**Issue by tvvignesh** [dotansimha/graphql-eslint#656]
**Is your feature request related to a problem? Please describe.**

When you have a schema like this (using `#graphql` for magic comments as used by [VSCode GraphQL](https://github.com/graphql/vscode-graphql) extension

```ts
import { Source } from 'graphql';

export const schema = new Source(
`#graphql

type User {
   field: Type!
},
__filename
);
```

GraphQL ESLint would not be able to pick this up. Adding support for `#graphql` would be great so that consistency can be maintained with the extension as well.

![image](https://user-images.githubusercontent.com/1165845/135084633-5d218e32-f131-4bbe-b405-858c1223c992.png)

**Describe the solution you'd like**

Support for `#graphql` for magic comments with usage as mentioned above

**Describe alternatives you've considered**

Requesting support for `/* GraphQL */ to VSCode GraphQL Extension.

**Comment by B2o5T** [comment]
Hi @tvvignesh, this is first time that I see `#graphql` magic comment, I personally prefer `/* GraphQL */` magic comments because:
1. `prettier` works out of box with `/* GraphQL */` and `/* HTML */` magic comments
2. you don't need to add unnecessary `#graphql` comment to your AST tree

I think you need to wait for support `/* GraphQL */` in `VSCode GraphQL Extension`

**Comment by tvvignesh** [comment]
@B2o5T Actually after reviewing the source code of VSCode GraphQL, looks like its already supported but just not documented by them.

![image](https://user-images.githubusercontent.com/1165845/135102154-a3ee966b-a2e2-4126-adbe-895554d644f7.png)

Maybe it makes sense to close this PR 👍🏼
